name: Daily update and deployment

on:
  schedule:
    - cron: '15 22 * * *'

jobs:
  update:
    name: Update Playlists
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run update script
        run: node scripts/updatePlaylists.js
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}

  deploy:
    name: Deploy
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy-to-aws.yml
    secrets:
      SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
