name: Deploy to Amazon S3 and CloudFront

on:
  workflow_call:
    secrets:
      SECRET_API_KEY:
        required: true
      AWS_ROLE_TO_ASSUME:
        required: true
      AWS_REGION:
        required: true
      S3_BUCKET:
        required: true
      AWS_DISTRIBUTION_ID:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    env:
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean install dependencies and build client
        run: |
          npm ci
          npm run build
        env:
          SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        uses: reggionick/s3-deploy@v4
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_REGION }}
          dist-id: ${{ secrets.AWS_DISTRIBUTION_ID }}
          invalidation: '/*'
          private: true
          delete-removed: true
