name: Deploy to Amazon S3 and CloudFront

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy-to-aws.yml
    secrets:
      SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
